StaticB_Node:
    ros__parameters:
      maxSteer: 27.2
      '/control/velocity': '/control/velocity'
      '/finisher/is_finished': '/finisher/is_finished'
      '/state': '/state'
      '/ros_can/ebs': '/ros_can/ebs'
      '/supervisor/driving_flag': '/supervisor/driving_flag'
